package utils
package utils

import (






























































































}	return str	str = regexp.MustCompile(`\s+`).ReplaceAllString(str, " ")	str = strings.TrimSpace(str)func SanitizeString(str string) string {// SanitizeString removes special characters and extra spaces}	return ""	}		return parts[1]	if len(parts) == 2 {	parts := strings.Split(email, "@")func ExtractDomain(email string) string {// ExtractDomain extracts domain from email address}	return false	}		}			return true		if strings.Contains(text, strings.ToLower(item)) {	for _, item := range items {	text = strings.ToLower(text)func ContainsAny(text string, items []string) bool {// ContainsAny checks if text contains any of the provided strings}	return time.Now()	}		}			return t		if t, err := time.Parse(format, dateStr); err == nil {	for _, format := range formats {	}		time.RFC2822,		time.RFC822,		"January 02, 2006",		"Jan 02 2006",		"02/01/2006",		"01/02/2006",		"2006-01-02",	formats := []string{func ParseDate(dateStr string) time.Time {// ParseDate parses various date formats}	return amount	}		return 0	if err != nil {	amount, err := strconv.ParseFloat(matches[0], 64)	}		return 0	if len(matches) == 0 {	matches := re.FindAllString(cleaned, 1)	re := regexp.MustCompile(`[\d.]+`)	// Find first number pattern	cleaned = strings.ReplaceAll(cleaned, ",", "")	cleaned = strings.ReplaceAll(cleaned, "£", "")	cleaned = strings.ReplaceAll(cleaned, "€", "")	cleaned := strings.ReplaceAll(text, "$", "")	// Remove common currency symbols and textfunc ExtractAmount(text string) float64 {// ExtractAmount extracts numeric amount from text}	return match	match := re.FindString(text)	re := regexp.MustCompile(`[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}`)func ExtractEmail(text string) string {// ExtractEmail extracts email address from a string}	return string(decoded)	}		return encoded	if err != nil {	decoded, err := base64.RawURLEncoding.DecodeString(encoded)func DecodeBase64(encoded string) string {// DecodeBase64 decodes base64 encoded string)	"time"	"strings"	"strconv"	"regexp"	"encoding/base64"